apiVersion: snowflying.io/v1alpha1
kind: NamespaceClass
metadata:
  name: development-resource-quota-limits
spec:
  resources:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: dev-quota
    spec:
      hard:
        requests.cpu: "4"
        requests.memory: 8Gi
        pods: "20"
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: dev-limits
    spec:
      limits:
      - max:
          cpu: "2"
          memory: 4Gi
        default:
          cpu: 500m
          memory: 512Mi
        type: Container
