apiVersion: snowflying.io/v1alpha1
kind: NamespaceClass
metadata:
  name: public-network
spec:
  resources:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-public-ingress
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
      ingress:
      - from:
        - ipBlock:
            cidr: 0.0.0.0/0
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: network-config
    data:
      network-type: "public"
      allow-external: "true"
