apiVersion: snowflying.io/v1alpha1
kind: NamespaceClass
metadata:
  name: team-rbac
spec:
  resources:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: team-admin
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: admin-role
    rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: team-admin-binding
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: admin-role
    subjects:
    - kind: ServiceAccount
      name: team-admin
