apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsc-controller
  namespace: default
  labels:
    app: nsc-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nsc-controller
  template:
    metadata:
      labels:
        app: nsc-controller
    spec:
      containers:
        - name: nsc-controller
          image: alizeedocker/nsc-controller:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      imagePullSecrets:
        - name: mywebapp-dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: nsc-controller-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: nsc-controller
